/**
 * @fileoverview Collects @page rules and resolves the cascaded page style for
 * a given page context.
 * @author Nicholas C. Zakas
 */

//-----------------------------------------------------------------------------
// Imports
//-----------------------------------------------------------------------------

import {
	type AtRule,
	type ComponentValue,
	type Declaration,
	isFunction,
	isIdent,
	isToken,
	parseComponentValues,
	trimWhitespace,
	withoutWhitespace,
} from "./css/parser.js";
import {
	type PageSelector,
	type PageSize,
	compareSpecificity,
	matchesNth,
	parseLength,
	parsePageSelectors,
	parsePageSize,
} from "./css/values.js";

//-----------------------------------------------------------------------------
// Types
//-----------------------------------------------------------------------------

export const MARGIN_BOX_NAMES = [
	"top-left-corner",
	"top-left",
	"top-center",
	"top-right",
	"top-right-corner",
	"left-top",
	"left-middle",
	"left-bottom",
	"right-top",
	"right-middle",
	"right-bottom",
	"bottom-left-corner",
	"bottom-left",
	"bottom-center",
	"bottom-right",
	"bottom-right-corner",
] as const;

export type MarginBoxName = (typeof MARGIN_BOX_NAMES)[number];

export interface PageRule {
	selectors: PageSelector[];
	declarations: Declaration[];
	marginBoxes: Map<MarginBoxName, Declaration[]>;
	footnote: Declaration[];
	/** Source order. */
	order: number;
}

export interface PageContext {
	/** The page name (from the `page` property), if any. */
	name?: string;
	/** 1-based index of the page in the document. */
	index: number;
	/** 1-based index of the page within its page group (run of same-named pages). */
	groupIndex: number;
	/** Whether this is the first page of the document. */
	first: boolean;
	/** Whether this is a blank page generated by a forced break. */
	blank: boolean;
	side: "left" | "right";
}

export interface Margins {
	top: number;
	right: number;
	bottom: number;
	left: number;
}

export interface PageStyle {
	size: PageSize;
	orientation?: string;
	margins: Margins;
	marks: { crop: boolean; cross: boolean };
	bleed: number;
	counterReset: [string, number][];
	counterIncrement: [string, number][];
	/** Remaining page-box declarations (background, border, padding, ...). */
	declarations: Declaration[];
	marginBoxes: Map<MarginBoxName, Declaration[]>;
	footnote: Declaration[];
}

export interface PageStyleOptions {
	defaultSize: PageSize;
	defaultMargin: number;
	fontSize: number;
	/**
	 * Resolves a custom property referenced with `var()` in a page
	 * declaration (e.g. `size: var(--page-width) var(--page-height)`).
	 * Returns undefined when the property is not defined.
	 */
	resolveVariable?: (name: string) => string | undefined;
}

//-----------------------------------------------------------------------------
// Collection
//-----------------------------------------------------------------------------

const MARGIN_BOX_SET = new Set<string>(MARGIN_BOX_NAMES);

/**
 * Converts a parsed @page at-rule into a page rule.
 * @param rule The at-rule.
 * @param order The source order.
 * @returns The page rule, or undefined if the selector is invalid.
 */
export function createPageRule(
	rule: AtRule,
	order: number,
): PageRule | undefined {
	if (rule.type !== "at" || rule.name.toLowerCase() !== "page") {
		throw new TypeError("Expected an @page rule.");
	}

	const selectors = parsePageSelectors(rule.prelude);

	if (!selectors) {
		return undefined;
	}

	const marginBoxes = new Map<MarginBoxName, Declaration[]>();
	const footnote: Declaration[] = [];

	for (const nested of rule.rules ?? []) {
		if (nested.type !== "at") {
			continue;
		}

		const name = nested.name.toLowerCase();

		if (MARGIN_BOX_SET.has(name)) {
			const boxName = name as MarginBoxName;
			const existing = marginBoxes.get(boxName) ?? [];
			existing.push(...(nested.declarations ?? []));
			marginBoxes.set(boxName, existing);
		} else if (name === "footnote") {
			footnote.push(...(nested.declarations ?? []));
		}
	}

	return {
		selectors,
		declarations: rule.declarations ?? [],
		marginBoxes,
		footnote,
		order,
	};
}

//-----------------------------------------------------------------------------
// Matching
//-----------------------------------------------------------------------------

/**
 * Determines whether a page selector matches a page context.
 * @param selector The page selector.
 * @param context The page context.
 * @returns True if the selector matches.
 */
export function matchesPage(
	selector: PageSelector,
	context: PageContext,
): boolean {
	if (selector.name !== undefined && selector.name !== context.name) {
		return false;
	}

	if (selector.first) {
		const isFirst =
			selector.name !== undefined
				? context.groupIndex === 1
				: context.first;

		if (!isFirst) {
			return false;
		}
	}

	if (selector.blank && !context.blank) {
		return false;
	}

	if (selector.left && context.side !== "left") {
		return false;
	}

	if (selector.right && context.side !== "right") {
		return false;
	}

	const nthIndex =
		selector.name !== undefined ? context.groupIndex : context.index;

	for (const nth of selector.nth) {
		if (!matchesNth(nth, nthIndex)) {
			return false;
		}
	}

	return true;
}

interface MatchedRule {
	rule: PageRule;
	specificity: [number, number, number];
}

/**
 * Finds the rules matching a page context, in cascade order (lowest priority first).
 * @param rules The page rules.
 * @param context The page context.
 * @returns The matching rules in cascade order.
 */
export function matchPageRules(
	rules: PageRule[],
	context: PageContext,
): PageRule[] {
	const matched: MatchedRule[] = [];

	for (const rule of rules) {
		let best: [number, number, number] | undefined;

		for (const selector of rule.selectors) {
			if (matchesPage(selector, context)) {
				if (
					!best ||
					compareSpecificity(selector.specificity, best) > 0
				) {
					best = selector.specificity;
				}
			}
		}

		if (best) {
			matched.push({ rule, specificity: best });
		}
	}

	matched.sort(
		(a, b) =>
			compareSpecificity(a.specificity, b.specificity) ||
			a.rule.order - b.rule.order,
	);

	return matched.map(entry => entry.rule);
}

//-----------------------------------------------------------------------------
// Cascade
//-----------------------------------------------------------------------------

/**
 * Cascades a list of declarations (already in priority order, lowest first),
 * honoring `!important`.
 * @param declarations The declarations.
 * @returns The winning declaration for each property, in first-seen order.
 */
export function cascadeDeclarations(
	declarations: Declaration[],
): Declaration[] {
	const result = new Map<string, Declaration>();
	const locked = new Set<string>();

	for (const declaration of declarations) {
		if (declaration.important) {
			result.set(declaration.name, declaration);
			locked.add(declaration.name);
		} else if (!locked.has(declaration.name)) {
			result.set(declaration.name, declaration);
		}
	}

	return [...result.values()];
}

function parseMarginShorthand(
	values: ComponentValue[],
	fontSize: number,
): Margins | undefined {
	const parts = withoutWhitespace(values);

	if (parts.length === 0 || parts.length > 4) {
		return undefined;
	}

	const lengths: number[] = [];

	for (const part of parts) {
		const length = isIdent(part, "auto") ? 0 : parseLength(part, fontSize);

		if (length === undefined) {
			return undefined;
		}

		lengths.push(length);
	}

	const [a, b = a, c = a, d = b] = lengths;
	return { top: a, right: b, bottom: c, left: d };
}

function parseCounterList(
	values: ComponentValue[],
): [string, number][] | undefined {
	const parts = withoutWhitespace(values);

	if (parts.length === 1 && isIdent(parts[0], "none")) {
		return [];
	}

	const result: [string, number][] = [];
	let index = 0;

	while (index < parts.length) {
		const nameValue = parts[index];

		if (!isIdent(nameValue)) {
			return undefined;
		}

		index++;
		let value: number | undefined;
		const next = parts[index];

		if (isToken(next, "number")) {
			value = next.number;
			index++;
		}

		result.push([nameValue.value, value ?? Number.NaN]);
	}

	return result;
}

const PAGE_ONLY_DESCRIPTORS = new Set([
	"size",
	"marks",
	"bleed",
	"page-orientation",
	"margin",
	"margin-top",
	"margin-right",
	"margin-bottom",
	"margin-left",
	"counter-reset",
	"counter-increment",
]);

/**
 * Resolves the page style for a page context by cascading the matching rules.
 * @param rules The page rules.
 * @param context The page context.
 * @param options Defaults used when the descriptors are not specified.
 * @returns The resolved page style.
 */
/**
 * Replaces `var()` references in a value with the resolved custom property
 * values (or their fallbacks). Unresolvable references are left in place.
 * @param values The component values.
 * @param resolve The custom property resolver.
 * @returns The substituted values.
 */
export function substituteVariables(
	values: ComponentValue[],
	resolve?: (name: string) => string | undefined,
): ComponentValue[] {
	if (!values.some(value => isFunction(value, "var"))) {
		return values;
	}

	const output: ComponentValue[] = [];

	for (const value of values) {
		if (!isFunction(value, "var")) {
			output.push(value);
			continue;
		}

		const parts = withoutWhitespace(value.value);
		const name = isIdent(parts[0]) ? parts[0].value : undefined;
		const resolved = name && resolve ? resolve(name)?.trim() : undefined;

		if (resolved) {
			output.push(
				...substituteVariables(parseComponentValues(resolved), resolve),
			);
			continue;
		}

		const comma = value.value.findIndex(part => isToken(part, "comma"));

		if (comma !== -1) {
			output.push(
				...substituteVariables(
					trimWhitespace(value.value.slice(comma + 1)),
					resolve,
				),
			);
			continue;
		}

		output.push(value);
	}

	return output;
}

export function resolvePageStyle(
	rules: PageRule[],
	context: PageContext,
	options: PageStyleOptions,
): PageStyle {
	const matching = matchPageRules(rules, context);
	const pageDeclarations = cascadeDeclarations(
		matching.flatMap(rule => rule.declarations),
	);
	const marginBoxes = new Map<MarginBoxName, Declaration[]>();
	const footnote = cascadeDeclarations(
		matching.flatMap(rule => rule.footnote),
	);

	for (const rule of matching) {
		for (const [name, declarations] of rule.marginBoxes) {
			const existing = marginBoxes.get(name) ?? [];
			existing.push(...declarations);
			marginBoxes.set(name, existing);
		}
	}

	for (const [name, declarations] of marginBoxes) {
		marginBoxes.set(name, cascadeDeclarations(declarations));
	}

	const { fontSize } = options;
	const style: PageStyle = {
		size: { ...options.defaultSize },
		margins: {
			top: options.defaultMargin,
			right: options.defaultMargin,
			bottom: options.defaultMargin,
			left: options.defaultMargin,
		},
		marks: { crop: false, cross: false },
		bleed: 0,
		counterReset: [],
		counterIncrement: [],
		declarations: [],
		marginBoxes,
		footnote,
	};

	let bleedAuto = true;

	for (const declaration of pageDeclarations) {
		const { name } = declaration;
		const value = substituteVariables(
			declaration.value,
			options.resolveVariable,
		);

		switch (name) {
			case "size": {
				const size = parsePageSize(
					value,
					options.defaultSize,
					fontSize,
				);

				if (size) {
					style.size = size;
				}

				break;
			}

			case "page-orientation": {
				const parts = withoutWhitespace(value);

				if (parts.length === 1 && isIdent(parts[0])) {
					style.orientation = parts[0].value.toLowerCase();
				}

				break;
			}

			case "margin": {
				const margins = parseMarginShorthand(value, fontSize);

				if (margins) {
					style.margins = margins;
				}

				break;
			}

			case "margin-top":
			case "margin-right":
			case "margin-bottom":
			case "margin-left": {
				const parts = withoutWhitespace(value);
				const length = isIdent(parts[0], "auto")
					? 0
					: parseLength(parts[0], fontSize);

				if (length !== undefined) {
					style.margins[name.slice(7) as keyof Margins] = length;
				}

				break;
			}

			case "marks": {
				const parts = withoutWhitespace(value);
				style.marks = { crop: false, cross: false };

				for (const part of parts) {
					if (isIdent(part, "crop")) {
						style.marks.crop = true;
					} else if (isIdent(part, "cross")) {
						style.marks.cross = true;
					}
				}

				break;
			}

			case "bleed": {
				const parts = withoutWhitespace(value);

				if (isIdent(parts[0], "auto")) {
					bleedAuto = true;
				} else {
					const length = parseLength(parts[0], fontSize);

					if (length !== undefined) {
						style.bleed = length;
						bleedAuto = false;
					}
				}

				break;
			}

			case "counter-reset": {
				const counters = parseCounterList(value);

				if (counters) {
					style.counterReset = counters.map(([counter, amount]) => [
						counter,
						Number.isNaN(amount) ? 0 : amount,
					]);
				}

				break;
			}

			case "counter-increment": {
				const counters = parseCounterList(value);

				if (counters) {
					style.counterIncrement = counters.map(
						([counter, amount]) => [
							counter,
							Number.isNaN(amount) ? 1 : amount,
						],
					);
				}

				break;
			}

			default:
				if (!PAGE_ONLY_DESCRIPTORS.has(name)) {
					style.declarations.push(declaration);
				}
		}
	}

	// bleed: auto computes to 6pt if marks has crop, otherwise 0
	if (bleedAuto) {
		style.bleed = style.marks.crop ? 8 : 0;
	}

	return style;
}
