name: Node CI

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest, macOS-latest, ubuntu-latest]
                node: [22.x, 24.x]

        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js ${{ matrix.node }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node }}
            - name: npm install, build, and test
              run: |
                  npm ci
                  npx puppeteer browsers install chrome
                  npm run build --if-present
                  npm run lint
                  npm test
              env:
                  CI: true

    test-firefox:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js lts/*
              uses: actions/setup-node@v7
              with:
                  node-version: lts/*
            - name: npm install, build, and test in Firefox
              run: |
                  npm ci
                  npx puppeteer browsers install firefox
                  npm run build --if-present
                  npm test
              env:
                  CI: true
                  BROWSER: firefox
